config/routes.rb
Rails.application.routes.draw do
	root 'pictures#index'
	get '/users/:id', to: 'users#show', as: 'home'
	
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@pictures = Picture.all
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
		@pictures = Picture.all
	end

	def create
		@picture = Picture.create(picture_params)

		if @picture.save
      		redirect_to pictures_path
    	else
			render 'new'
		end
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update(picture_params)
			redirect_to pictures_path
		else
			render 'edit'
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_path
	end 	

	private

	def picture_params
		params.require(:picture).permit(:image, :title, :user_id)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	before_action :authenticate_user! 
	
  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@pictures = Picture.all
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogalery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		<ul class="nav nav-tabs">
  			<li class="active"><%= link_to 'Фотогалерея', root_path %></li>
  			<% if user_signed_in? %>
  				<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
  				<li>'Hello!'<%= link_to current_user.user_name, edit_user_registration_path(current_user) %></li>
  			<% else %>
  				<li><%= link_to 'Sign in', new_user_session_path %></li>
  				<li><%= link_to 'Register', new_user_registration_path %></li>
  			<% end -%>
		</ul>
    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.erb
<h1>photogalery</h1>

<div class="container">
		<table class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Picture</th>
			</tr>
			<% @pictures.each do |inform| %>
				<tr>
					<td><%= inform.name %></td>
				</tr>
		</table>
		<% end -%>
</div>

app/views/pictures/my_page.html.erb
<h1>Home page</h1>

<%= link_to 'Add image', new_picture_path %>
<div class="container">
		<table class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Picture</th>
			</tr>
			<% @pictures.each do |pic| %>
				<tr>
					<td><%= inform.name %></td>
					<td><%= link_to 'Delete', picture_path(pic),
					method: :delete,
					data: {confirm: "Are you sure?"} %></td>
				</tr>
		</table>
		<% end -%>

app/views/pictures/new.html.erb
<h1>Home page</h1>

<%= link_to 'Add image', new_picture_path %>
<div class="container">
		<table class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Picture</th>
			</tr>
			<% @pictures.each do |pic| %>
				<tr>
					<td><%= inform.title %></td>
					<td><%= link_to 'Delete', picture_path(pic),
					method: :delete,
					data: {confirm: "Are you sure?"} %></td>
				</tr>
		</table>
		<% end -%>

app/views/users/show.html.erb
<h1>Home page</h1>

<%= link_to 'Add image', new_picture_path %>
<div class="container">
		<table class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Picture</th>
			</tr>
			<% @pictures.each do |pic| %>
				<tr>
					<td><%= inform.title %></td>
					<td><%= link_to 'Delete', new_picture_path(pic),
					method: :delete,
					data: {confirm: "Are you sure?"} %></td>
				</tr>
		</table>
		<% end -%>